matrixorigin/CI

.github/workflows/e2e-standalone.yaml

change multi cn mode with proxy to dynamic in release/1.1-dev

change multi cn mode with proxy to dynamic

---

.github/workflows/ci.yaml

issue: https://github.com/matrixorigin/MO-Cloud/issues/3397
need wait pr https://github.com/matrixorigin/matrixone/pull/16604 merged

print result at end

---

.github/workflows/ci.yaml

issue: https://github.com/matrixorigin/CI/pull/65#issue-2332683866
wait pr https://github.com/matrixorigin/matrixone/pull/16644 to be merged

Optimize ut for branch 1.2-dev

---

.github/workflows/robot.yaml

Change milestone Settings

---

.github/workflows/robot.yaml
actions/reopen-without-PR/action.yml
actions/reopen-without-PR/main.go
actions/reopen-without-PR/pkg/config/config.go
actions/reopen-without-PR/pkg/config/get.go

测试action：https://github.com/Rosyrain/github_action_test/actions/runs/10667720359/job/29565864394
测试issue：https://github.com/Rosyrain/github_action_test/issues/19
测试结果：

reconfiguration reopen-without-PR action

---

actions/reopen-without-PR/main.go

测试action: https://github.com/Rosyrain/github_action_test/actions/runs/10825651881/job/30035020572
测试issue: https://github.com/Rosyrain/github_action_test/issues/92
测试结果: issue拥有者可以直接关闭issue，不做后续处理

update logic for issue-owner

---

.github/workflows/utils.yaml

issue: https://github.com/matrixorigin/matrixone/issues/18792

remove special pkgs

---

.github/workflows/e2e-standalone.yaml

测试:https://github.com/Rosyrain/matrixone/actions/runs/11252038549/job/31284333676

upload e2e-standlone.yaml mo-r1-log

---

.github/workflows/check-action-file.yaml
.github/workflows/ci.yaml
.github/workflows/e2e-compose.yaml
.github/workflows/e2e-standalone.yaml
.github/workflows/e2e-upgrade.yaml
.github/workflows/image-build.yaml
.github/workflows/merge-trigger-standalone.yaml
.github/workflows/merge-trigger-tke.yaml
.github/workflows/release.yaml
.github/workflows/robot.yaml
.github/workflows/utils.yaml

相关测试链接
1. wewrok robot--`nightly-check`: https://github.com/Rosyrain/matrixone/actions/runs/11286206158/job/31390199730
2. Build and Push Images: https://github.com/Rosyrain/matrixone/actions/runs/11286896571
3. Release: https://github.com/Rosyrain/matrixone/actions/runs/11286939650
4. PR测试: https://github.com/Rosyrain/matrixone/actions/runs/11286202429
5. MO Checkin Regression On TKE: https://github.com/Rosyrain/matrixone/actions/runs/11286829819
6. MO Checkin Regression(Standalone BVT): https://github.com/Rosyrain/matrixone/actions/runs/11286829820
<br>
链1,2,3失败原因，没有正确的对应密钥，与本次修改无关
<br>
链接3,5,6由于没有对应的机器进行取消。但可以从图中得知，已经正常调用。

update environment secrets

---

scripts/parse_coverage.py

测试链接
https://github.com/Rosyrain/matrixone/actions/runs/11401110216/job/31723344952

optimize python skip files and outputs

---

.github/workflows/robot.yaml
.github/workflows/utils.yaml

修复ut test时因为 `| tee xxx.out`导致退出状态码为0，无法正常捕获panic
测试链接，已成功捕获panic
https://github.com/Rosyrain/matrixone/actions/runs/11382671038/job/31666674954
https://github.com/Rosyrain/matrixone/actions/runs/11382666089/job/31666680799

fix ut panic Exit-Code

---

.github/workflows/merge-trigger-tke.yaml

测试链接: https://github.com/matrixorigin/ci-test/actions/runs/11571090037

update tke ssb-tpch test user

---

.github/workflows/merge-trigger-tke.yaml

测试链接
https://github.com/matrixorigin/ci-test/actions/runs/11625570594/job/32376203514

update tpcc 50w50t

---

.github/workflows/e2e-upgrade.yaml

测试链接：https://github.com/Rosyrain/matrixone/actions/runs/11793862861/job/32851036005

Update Tagname 1.2dev

---

.github/workflows/ci.yaml

测试链接：https://github.com/Rosyrain/matrixone/actions/runs/11853628292/job/33122148168
对应MO需要增加相关MOC的secret传递：https://github.com/matrixorigin/matrixone/pull/20147

Insert failed ut cases to MOC

---

.github/workflows/utils.yaml

新测试：https://github.com/matrixorigin/ci-test/actions/runs/11736506236/job/32695871777#step:2:1
时间短的是准备数据阶段
UT:10m10s
BVT:1m17s+21m44s
TPCC:1m36s+5m1s
sysbench:38s+5m13s
SSB:2m18s
TPCH:1m53s+2m11s
总耗时：55m14s

add other test for coverage

---

.github/workflows/utils.yaml

Revert "fix ci name"

---

.github/workflows/e2e-upgrade.yaml

测试link：https://github.com/Rosyrain/matrixone/actions/runs/12027093858/job/33527442111

download reports and mo-data

---

.github/workflows/ci.yaml
.github/workflows/utils.yaml

测试link：https://github.com/Rosyrain/matrixone/actions/runs/12054633487/job/33613149076

New failed-ut-case action

---

.github/workflows/ci.yaml
.github/workflows/utils.yaml

测试link: https://github.com/Rosyrain/matrixone/actions/runs/12054633487/job/33613149076

Insert failed ut case to moc for 2.0dev

---

.github/dependabot.yaml

Revert "change dependabot pr number"

---

.github/workflows/utils.yaml

add thirdparties shared library.

add thirdparties

---

.github/workflows/utils.yaml

add thirdparties shared library.

make GOBUILD_OPT=-cover
